name: My CI Actions
on:
  workflow_dispatch:
  push:
    branches:
      - 'master' # Set branch of the GH repo to push
jobs:
  test_suite: # Name of the job
      runs-on: ubuntu-20.04 # Choosing OS
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.2' # In command line run “node -v” and choose your version
      - run: npm ci 
#      - run: npm config set script-shell "C:\Program Files\Git\bin\bash.exe"
      - name: run test
        run: npm run test:headless # Our name of the headless script
      - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs